# Generated by Django 5.2.8 on 2025-11-22 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('complaints', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaint',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.subcategory'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaint',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='complaintattachment',
            name='complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='complaints.complaint'),
        ),
        migrations.AddField(
            model_name='complaintattachment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='complaintcomment',
            name='complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='complaints.complaint'),
        ),
        migrations.AddField(
            model_name='complaintcomment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='complaintcomment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['tenant', 'reference'], name='complaints__tenant__991c35_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['tenant', 'status'], name='complaints__tenant__b87b04_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['tenant', 'submitted_at'], name='complaints__tenant__457c50_idx'),
        ),
        migrations.AddIndex(
            model_name='complaintattachment',
            index=models.Index(fields=['tenant', 'complaint'], name='complaints__tenant__43a364_idx'),
        ),
        migrations.AddIndex(
            model_name='complaintcomment',
            index=models.Index(fields=['tenant', 'complaint'], name='complaints__tenant__2a0f08_idx'),
        ),
    ]
