# Generated by Django 5.2.8 on 2025-11-26 02:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('complaints', '0002_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('complaint_reference', models.CharField(max_length=64)),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('STATUS_CHANGED', 'Status Changed'), ('ASSIGNED', 'Assigned'), ('REASSIGNED', 'Reassigned'), ('COMMENT_ADDED', 'Comment Added'), ('ATTACHMENT_ADDED', 'Attachment Added'), ('UPDATED', 'Updated'), ('DELETED', 'Deleted')], max_length=30)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SLAConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('urgency_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('delay_hours', models.PositiveIntegerField(help_text='Allowed hours to respect SLA for this combo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AlterModelOptions(
            name='complaintcomment',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='complaintattachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='categories.category'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='categories.subcategory'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['tenant', 'urgency'], name='complaints__tenant__1901b7_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['assigned_user', 'status'], name='complaints__assigne_c2a26e_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['sla_deadline'], name='complaints__sla_dea_f49b84_idx'),
        ),
        migrations.AddField(
            model_name='complainthistory',
            name='complaint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='complaints.complaint'),
        ),
        migrations.AddField(
            model_name='complainthistory',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='complainthistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='slaconfig',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_configs', to='categories.category'),
        ),
        migrations.AddField(
            model_name='slaconfig',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='complainthistory',
            index=models.Index(fields=['tenant', 'complaint'], name='complaints__tenant__0a7b01_idx'),
        ),
        migrations.AddIndex(
            model_name='complainthistory',
            index=models.Index(fields=['tenant', 'created_at'], name='complaints__tenant__01a799_idx'),
        ),
        migrations.AddIndex(
            model_name='complainthistory',
            index=models.Index(fields=['action'], name='complaints__action_549bd4_idx'),
        ),
        migrations.AddIndex(
            model_name='slaconfig',
            index=models.Index(fields=['tenant', 'category', 'urgency_level'], name='complaints__tenant__029940_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='slaconfig',
            unique_together={('tenant', 'category', 'urgency_level')},
        ),
    ]
